# Generated by Django 3.1.7 on 2021-04-22 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210411_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating should be >= 0')]),
        ),
    ]
